const fs = require("fs");
const src = fs.readFileSync(__dirname + "/song-request.js", "utf8");
const test = [
  ";console.log(JSON.stringify({",
  "  run: typeof exports.run,",
  "  getDefaultParameters: typeof exports.getDefaultParameters,",
  "  getScriptManifest: typeof exports.getScriptManifest,",
  "}));",
  "console.log(JSON.stringify(exports.getDefaultParameters()));",
  "const v = 'dBjftJeZ4CVP-mB92K27uhbUJU1p1r_wW1gFWFOEjXk';",
  "console.log('challenge:', codeChallengeFrom(v));",
  "const u = 'https://accounts.spotify.com/authorize?response_type=code&client_id=abc&code_challenge=x';",
  "const a = browserArgs('win32', u);",
  "console.log('win32 args:', JSON.stringify(a));",
  "console.log('win32 url passed as one quoted token:', a.args[3] === '\"' + u + '\"');",
  "console.log('win32 empty title placeholder before url:', a.args[2] === '\"\"' && a.args[0] === '/c' && a.args[1] === 'start');",
  "console.log('win32 windowsVerbatimArguments set:', a.options && a.options.windowsVerbatimArguments === true);",
  "console.log('redirect uri uses loopback ip not localhost:', redirectUriFor(8899) === 'http://127.0.0.1:8899/callback' && !redirectUriFor(8899).includes('localhost'));",
  "const os = require('os');",
  "dataDir = path.join(os.tmpdir(), 'fsr-test-' + Date.now(), 'missing', 'nested');",
  "saveTokens({ accessToken: 'tok', refreshToken: 'ref', expiresAt: Date.now() + 1000 });",
  "const saved = loadTokens();",
  "console.log('save tokens into missing nested dir works:', !!saved && saved.accessToken === 'tok' && saved.refreshToken === 'ref');",
  "clearTokens(); dataDir = null;",
  "console.log('queue endpoint is POST /me/player/queue with device_id and uri:', queueEndpoint('dev 1', 'spotify:track:abc&x') === '/me/player/queue?device_id=dev%201&uri=spotify%3Atrack%3Aabc%26x');",
  "const q1 = extractQuery({ type: 'command', metadata: { commandName: 'ssr', userCommand: { command: 'ssr', args: ['beautiful', 'people', '-', 'marilyn', 'manson'] } } });",
  "console.log('extractQuery joins args:', q1 === 'beautiful people - marilyn manson');",
  "const q2 = extractQuery({ type: 'command', metadata: { commandName: 'ssr', userCommand: { command: 'ssr', args: ['!ssr'] } } });",
  "console.log('extractQuery strips leading command token so bare command shows usage:', q2 === '');",
  "const q3 = extractQuery({ type: 'command', metadata: { commandName: 'ssr', userCommand: { command: 'ssr', args: [] } } });",
  "console.log('extractQuery empty args stays empty:', q3 === '');",
  "const q4 = extractQuery({ type: 'command', metadata: { userCommand: { args: ['!ssr', 'nickelback', 'photograph'] } } });",
  "console.log('extractQuery strips leading !command token without commandName metadata:', q4 === 'nickelback photograph');",
  "const q5 = extractQuery({ type: 'command', metadata: { userCommand: { args: ['!ssr nickelback photograph'] } } });",
  "console.log('extractQuery strips command token when whole message is one arg:', q5 === 'nickelback photograph');",
  "const q6 = extractQuery({ type: 'command', metadata: { userCommand: { args: ['!ssr'] } } });",
  "console.log('extractQuery bare prefixed command yields empty so usage shows:', q6 === '');",
  "const c1 = searchCandidates('beautiful people - marilyn manson');",
  "console.log('hyphen query becomes structured track/artist search:', c1[0] === 'track:\"beautiful people\" artist:\"marilyn manson\"');",
  "console.log('reversed artist/title order tried as fallback:', c1[1] === 'track:\"marilyn manson\" artist:\"beautiful people\"');",
  "console.log('no bare hyphen operator left outside quoted phrases:', c1.every((c) => !/[-–—]/.test(c.replace(/\"[^\"]*\"/g, '\"\"'))));",
  "const c2 = searchCandidates('Bohemian Rhapsody');",
  "console.log('plain query quoted as track search:', c2[0] === 'track:\"Bohemian Rhapsody\"' && c2.length === 1);",
  "const c3 = searchCandidates('cats (live) AND hounds');",
  "console.log('free-text fallback strips spotify operators:', c3[c3.length - 1] === 'cats live hounds');",
  "const l1 = parseSpotifyLink('https://open.spotify.com/track/1lRmQ9D6oNYiuCXdGlKCs0?si=81596043d06e43c0');",
  "console.log('track url with si param parsed:', !!l1 && l1.type === 'track' && l1.id === '1lRmQ9D6oNYiuCXdGlKCs0');",
  "const l2 = parseSpotifyLink('https://open.spotify.com/intl-de/track/1lRmQ9D6oNYiuCXdGlKCs0');",
  "console.log('intl track url parsed:', !!l2 && l2.type === 'track' && l2.id === '1lRmQ9D6oNYiuCXdGlKCs0');",
  "const l3 = parseSpotifyLink('spotify:track:1lRmQ9D6oNYiuCXdGlKCs0');",
  "console.log('spotify uri parsed:', !!l3 && l3.type === 'track' && l3.id === '1lRmQ9D6oNYiuCXdGlKCs0');",
  "const l4 = parseSpotifyLink('https://open.spotify.com/playlist/37i9dQZF1DXcBWIGoYBM5M');",
  "console.log('playlist url detected as non-track:', !!l4 && l4.type === 'playlist');",
  "console.log('plain text is not a link:', parseSpotifyLink('nickelback photograph') === null);"
].join("\n");
fs.writeFileSync(__dirname + "/test-src.js", src + test);
